# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib {
  {D:/Facultad/Arqui 1/Arqui Entrega Lab/Arqui1Entrega/Arqui1Entrega/Arqui1Entrega.srcs/sources_1/imports/sources_1/new/Registers.vhd}
  {D:/Facultad/Arqui 1/Arqui Entrega Lab/Arqui1Entrega/Arqui1Entrega/Arqui1Entrega.srcs/sources_1/imports/sources_1/new/ALU.vhd}
  {D:/Facultad/Arqui 1/Arqui Entrega Lab/Arqui1Entrega/Arqui1Entrega/Arqui1Entrega.srcs/sources_1/imports/sources_1/imports/MaterialLab2/ControlUnit.vhd}
  {D:/Facultad/Arqui 1/Arqui Entrega Lab/Arqui1Entrega/Arqui1Entrega/Arqui1Entrega.srcs/sources_1/imports/sources_1/imports/MaterialLab2/Multicycle_MIPS.vhd}
}
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Facultad/Arqui 1/Arqui Entrega Lab/Arqui1Entrega/Arqui1Entrega/Arqui1Entrega.cache/wt} [current_project]
set_property parent.project_dir {D:/Facultad/Arqui 1/Arqui Entrega Lab/Arqui1Entrega/Arqui1Entrega} [current_project]
synth_design -top Multicycle_MIPS -part xc7z020clg484-1
write_checkpoint Multicycle_MIPS.dcp
report_utilization -file Multicycle_MIPS_utilization_synth.rpt -pb Multicycle_MIPS_utilization_synth.pb
